packages:
  - apps/*
  - packages/*
autoInstallPeers: true
minimumReleaseAge: 4320
allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  core-js: true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  supabase: true
